---
- name: install docker-engine on Debian Jessie
  hosts: swarm_manager_hosts
  sudo: yes
  tasks:
    - name: gather machine info
      setup:

    - name: update apt source
      apt:
         update_cache: yes

    - name: remove old version
      apt:
         name: "{{ item }}"
         state: absent
      with_items:
         - lxc-docker*
         - docker.io*
      ignore_errors: yes

    - name: install prerequisites and docker engine
      apt:
         name: "{{ item }}"
         state: present
      with_items:
         - apt-transport-https
         - ca-certificates
         - gnupg2

    - name: add new GPG key
      apt_key:
         keyserver: hkp://ha.pool.sks-keyservers.net:80
         id: 58118E89F3A912897C070ADBF76221572C52609D
   
    - name: add a docker apt repo
      apt_repository:
         repo: deb https://apt.dockerproject.org/repo debian-jessie main
         filename: docker
         state: present

    - name: update apt source again
      apt:
         update_cache: yes

    - name: install docker engine
      apt:
         name: docker-engine
         state: present
      notify: start docker daemon

    - name: start dockerd
      service:
         name: docker
         state: started

    - name: levae swarm mode first
      shell: docker swarm leave --force
      ignore_errors: yes
      when: inventory_hostname in groups['swarm_manager_init']

    - name: swarm mode init
      shell: docker swarm init --advertise-addr {{ansible_eth1.ipv4.address}}
      when: inventory_hostname in groups['swarm_manager_init']

    - name: swarm mode join info
      shell: docker swarm join-token -q manager
      register: swarm_join_manager_token
      delegate_to: manager_init
      when: inventory_hostname in groups['swarm_managers']

    - name: other swarm manager join cluster
      shell: docker swarm join --token {{swarm_join_manager_token.stdout}} {{hostvars['manager_init']['ansible_eth1']['ipv4']['address']}}:2377
      when: inventory_hostname in groups['swarm_managers']

  handlers:
    - name: start docker daemon
      service:
         name: docker
         state: started
