    - name: gather machine info
      setup:

    - name: update apt source
      apt:
         update_cache: yes

    - name: remove old version
      apt:
         name: "{{ item }}"
         state: absent
      with_items:
         - lxc-docker*
         - docker.io*
      ignore_errors: yes

    - name: install prerequisites and docker engine
      apt:
         name: "{{ item }}"
         state: present
      with_items:
         - apt-transport-https
         - ca-certificates
         - gnupg2

    - name: add new GPG key
      apt_key:
         keyserver: hkp://ha.pool.sks-keyservers.net:80
         id: 58118E89F3A912897C070ADBF76221572C52609D
   
    - name: add a docker apt repo
      apt_repository:
         repo: deb https://apt.dockerproject.org/repo debian-jessie main
         filename: docker
         state: present

    - name: update apt source again
      apt:
         update_cache: yes

    - name: install docker engine
      apt:
         name: docker-engine
         state: present

    - name: start dockerd
      service:
         name: docker
         state: started
 
    - name: add netease accelarate
      shell: echo "DOCKER_OPTS=\"\$DOCKER_OPTS --registry-mirror=http://hub-mirror.c.163.com\"" >> /etc/default/docker

    - name: start dockerd
      service:
         name: docker
         state: restarted
